# Generated by Django 3.0.3 on 2020-02-16 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='character',
            field=models.CharField(choices=[('BU', 'Bukko'), ('HO', 'Hojo'), ('KE', 'Kejsaren'), ('LA', 'Lapsang'), ('ME', 'Mentorn'), ('MP', 'Marco Polo'), ('TO', 'Tomoe')], max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
