# Generated by Django 3.0.3 on 2020-02-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_love'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='group',
            field=models.CharField(choices=[('DET', 'Dekor'), ('DIR', 'Directionen'), ('KM', 'KM'), ('KSP', 'KSP'), ('LED', 'Ledningen'), ('MAN', 'Manus'), ('MUS', 'Musikgruppen'), ('ORK', 'Orkestern'), ('SKA', 'Skådis'), ('TEK', 'Tekniken'), ('UPP', 'Uppsättningen')], max_length=3),
        ),
    ]
